/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AccountEndOfDayDocument {
  data: AccountEndOfDayResource;
}
export interface AccountEndOfDayResource {
  type: "accountEndOfDay";
  id: string;
  attributes: {
    date: string;
    balance: number;
    hold: number;
    available: number;
    overdraftLimit?: number;
  };
  relationships: Relationships;
}
export interface Relationships {
  customer?: {
    data: {
      type: "customer";
      id: string;
    };
  };
  account: {
    data: {
      type: "account";
      id: string;
    };
  };
}
