/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AddAuthorizedUsers {
  data: AddAuthorizedUsers1;
}
export interface AddAuthorizedUsers1 {
  type: "addAuthorizedUsers";
  attributes: {
    authorizedUsers: AuthorizedUser[];
  };
}
export interface AuthorizedUser {
  fullName: FullName;
  email: string & string & string;
  phone: Phone | Phone1;
  jwtSubject?: string | null;
}
export interface FullName {
  first: string;
  last: string;
}
export interface Phone {
  countryCode: string;
  number: string;
}
export interface Phone1 {
  countryCode: string;
  number: string;
}
