/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CardLevelLimitsResource {
  data: CardLevelLimits;
}
export interface CardLevelLimits {
  type: "limits";
  attributes: {
    limits?: CardLevelLimits1;
    dailyTotals: CardTotals;
    monthlyTotals: CardTotals;
  };
}
export interface CardLevelLimits1 {
  dailyWithdrawal?: number;
  dailyPurchase?: number;
  monthlyWithdrawal?: number;
  monthlyPurchase?: number;
}
export interface CardTotals {
  withdrawals: number;
  deposits: number;
  purchases: number;
  cardTransactions: number;
}
