/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CardResource =
  | BusinessDebitCard
  | IndividualDebitCard
  | BusinessVirtualDebitCard
  | IndividualVirtualDebitCard
  | BusinessCreditCard
  | BusinessVirtualCreditCard;

export interface CardsDocument {
  data: CardResource[];
}
export interface BusinessDebitCard {
  type: "businessDebitCard";
  id: string;
  attributes: {
    createdAt: string;
    updatedAt?: string;
    last4Digits: string;
    expirationDate: string;
    shippingAddress?: Address | Address1 | Address2;
    address: Address | Address1 | Address2;
    fullName: FullName;
    phone: Phone | Phone1;
    email: string & string & string;
    dateOfBirth: string;
    nationality?: string;
    ssn?: string;
    passport?: string;
    status?:
      | "Active"
      | "Inactive"
      | "Stolen"
      | "Lost"
      | "Frozen"
      | "ClosedByCustomer"
      | "Unknown"
      | "SuspectedFraud"
      | "DigitallyActive";
    design?: string;
    tags?: Tags;
    freezeReason?: string;
  };
  relationships: Relationships;
}
export interface Address {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "US";
}
export interface Address1 {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "CA";
}
export interface Address2 {
  street: string;
  street2?: string | null;
  city: string;
  state?: null | string;
  postalCode: string;
  country: string;
}
export interface FullName {
  first: string;
  last: string;
}
export interface Phone {
  countryCode: string;
  number: string;
}
export interface Phone1 {
  countryCode: string;
  number: string;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface Relationships {
  account: {
    data: {
      type: "account" | "depositAccount";
      id: string;
    };
  };
  customer?: {
    data: {
      type: "businessCustomer" | "individualCustomer" | "customer";
      id: string;
    };
  };
}
export interface IndividualDebitCard {
  type: "individualDebitCard";
  id: string;
  attributes?: {
    createdAt: string;
    updatedAt?: string;
    last4Digits: string;
    expirationDate: string;
    shippingAddress?: Address | Address1 | Address2;
    status:
      | "Active"
      | "Inactive"
      | "Stolen"
      | "Lost"
      | "Frozen"
      | "ClosedByCustomer"
      | "Unknown"
      | "SuspectedFraud"
      | "DigitallyActive";
    design?: string;
    tags?: Tags;
    freezeReason?: string;
  };
  relationships: Relationships;
}
export interface BusinessVirtualDebitCard {
  type: "businessVirtualDebitCard";
  id: string;
  attributes: {
    createdAt: string;
    updatedAt?: string;
    last4Digits: string;
    expirationDate: string;
    address: Address | Address1 | Address2;
    fullName: FullName;
    phone: Phone | Phone1;
    email: string & string & string;
    dateOfBirth: string;
    nationality?: string;
    ssn?: string;
    passport?: string;
    status?: "Active" | "Inactive" | "Stolen" | "Lost" | "Frozen" | "ClosedByCustomer" | "Unknown" | "SuspectedFraud";
    tags?: Tags;
    freezeReason?: string;
  };
  relationships: Relationships;
}
export interface IndividualVirtualDebitCard {
  type: "individualVirtualDebitCard";
  id: string;
  attributes?: {
    createdAt: string;
    updatedAt?: string;
    last4Digits: string;
    expirationDate: string;
    status: "Active" | "Inactive" | "Stolen" | "Lost" | "Frozen" | "ClosedByCustomer" | "Unknown" | "SuspectedFraud";
    tags?: Tags;
    freezeReason?: string;
  };
  relationships: Relationships;
}
export interface BusinessCreditCard {
  type: "businessCreditCard";
  id: string;
  attributes: {
    createdAt: string;
    updatedAt?: string;
    last4Digits: string;
    expirationDate: string;
    shippingAddress?: Address | Address1 | Address2;
    address: Address | Address1 | Address2;
    fullName: FullName;
    phone: Phone | Phone1;
    email: string & string & string;
    dateOfBirth: string;
    nationality?: string;
    ssn?: string;
    passport?: string;
    status?:
      | "Active"
      | "Inactive"
      | "Stolen"
      | "Lost"
      | "Frozen"
      | "ClosedByCustomer"
      | "Unknown"
      | "SuspectedFraud"
      | "DigitallyActive";
    design?: string;
    tags?: Tags;
    freezeReason?: string;
  };
  relationships: Relationships;
}
export interface BusinessVirtualCreditCard {
  type: "businessVirtualCreditCard";
  id: string;
  attributes: {
    createdAt: string;
    updatedAt?: string;
    last4Digits: string;
    expirationDate: string;
    address: Address | Address1 | Address2;
    fullName: FullName;
    phone: Phone | Phone1;
    email: string & string & string;
    dateOfBirth: string;
    nationality?: string;
    ssn?: string;
    passport?: string;
    status?: "Active" | "Inactive" | "Stolen" | "Lost" | "Frozen" | "ClosedByCustomer" | "Unknown" | "SuspectedFraud";
    tags?: Tags;
    freezeReason?: string;
  };
  relationships: Relationships;
}
