/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ChargebacksResource {
  data: Chargeback[];
}
export interface Chargeback {
  type: "chargeback";
  id: string;
  attributes: {
    description: string;
    amount: number;
    createdAt: string;
    tags: Tags;
  };
  relationships: Relationships;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface Relationships {
  customer: {
    data: {
      type: "businessCustomer" | "individualCustomer" | "customer";
      id: string;
    };
  };
  account: {
    data: {
      type: "account" | "depositAccount" | "batchAccount";
      id: string;
    };
  };
  counterpartyAccount: {
    data: {
      type: "account" | "depositAccount" | "batchAccount";
      id: string;
    };
  };
  transaction: {
    data: {
      type: "transaction";
      id: string;
    };
  };
}
