/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CheckDepositsResource {
  data: CheckDeposit[];
}
export interface CheckDeposit {
  type: "checkDeposit";
  id: string;
  attributes: {
    createdAt: string;
    settlementDate?: string;
    amount: number;
    description: string;
    status:
      | "AwaitingImages"
      | "AwaitingFrontImage"
      | "AwaitingBackImage"
      | "Pending"
      | "PendingReview"
      | "PendingCustomerReview"
      | "Rejected"
      | "Clearing"
      | "Sent"
      | "Canceled"
      | "Returned";
    reason?: string | null;
    statusCreatedAt?: string;
    statusSetBy?: string;
    reasonText?: string;
    checkNumber?: string;
    counterparty?: Counterparty;
    tags?: Tags;
  };
  relationships: Relationships;
}
export interface Counterparty {
  routingNumber: string;
  accountNumber: string;
  name: string;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface Relationships {
  org?: OrgRelationship;
  account: {
    data: {
      type: "account" | "depositAccount" | "batchAccount";
      id: string;
    };
  };
  customer?: {
    data: {
      type: "businessCustomer" | "individualCustomer" | "customer";
      id: string;
    };
  };
  transaction?: {
    data: {
      type: "transaction";
      id: string;
    };
  };
}
export interface OrgRelationship {
  data: {
    id: string;
    type: "org";
  };
}
