/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CloseAccount {
  data?: CloseDepositAccount | CloseCreditAccount;
}
export interface CloseDepositAccount {
  type: "accountClose" | "depositAccountClose";
  attributes: CloseAccountByCustomer | CloseAccountFraud;
  additionalProperties?: false;
}
export interface CloseAccountByCustomer {
  reason?: "ByCustomer";
  reasonText?: string;
}
export interface CloseAccountFraud {
  reason?: "Fraud";
  reasonText?: string;
  fraudReason?:
    | "ACHActivity"
    | "CardActivity"
    | "CheckActivity"
    | "ApplicationHistory"
    | "AccountActivity"
    | "ClientIdentified"
    | "IdentityTheft"
    | "LinkedToFraudulentCustomer";
}
export interface CloseCreditAccount {
  type: "creditAccountClose";
  attributes: CloseAccountByCustomer1 | CloseAccountByOverdue | CloseAccountFraud1;
  additionalProperties?: false;
}
export interface CloseAccountByCustomer1 {
  reason?: "ByCustomer";
  reasonText?: string;
}
export interface CloseAccountByOverdue {
  reason?: "Overdue";
  reasonText?: string;
}
export interface CloseAccountFraud1 {
  reason?: "Fraud";
  reasonText?: string;
  fraudReason?:
    | "ACHActivity"
    | "CardActivity"
    | "CheckActivity"
    | "ApplicationHistory"
    | "AccountActivity"
    | "ClientIdentified"
    | "IdentityTheft"
    | "LinkedToFraudulentCustomer";
}
