/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CounterpartyDocument {
  data: CounterpartyResource;
}
export interface CounterpartyResource {
  type: "achCounterparty";
  id: string;
  attributes?: {
    routingNumber: string;
    accountNumber: string;
    accountType: "Checking" | "Savings";
    type: "Business" | "Person" | "Unknown";
    name: string;
    bank?: string;
    permissions: "CreditOnly" | "DebitOnly" | "CreditAndDebit";
    tags?: Tags;
    createdAt: string;
  };
  relationships: Relationships;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface Relationships {
  customer: {
    data: {
      type: "customer";
      id: string;
    };
  };
}
