/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateSimulatedPurchaseReversal {
  data: CreateSimulatedPurchaseReversal1;
}
export interface CreateSimulatedPurchaseReversal1 {
  type: "cardReversalTransaction";
  attributes: {
    amount: number;
    last4Digits?: string;
    internationalServiceFee?: number;
  };
  relationships: Relationships;
}
export interface Relationships {
  account: {
    data: {
      type: "depositAccount" | "creditAccount";
      id: string;
    };
  };
  relatedTransaction?: {
    data: {
      type: "transaction";
      id: string;
    };
  };
}
