/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreatePartnerOnBehalfTokenRequest {
  data: CreatePartnerOnBehalfTokenRequest1;
}
export interface CreatePartnerOnBehalfTokenRequest1 {
  type: "createOnBehalfToken";
  attributes: {
    orgId: string;
    scopes: string;
    expiresIn?: number;
    sourceIp?: string;
  };
}
