/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateSimulatedAuthorization {
  data: CreateSimulatedAuthorization1;
}
export interface CreateSimulatedAuthorization1 {
  type: "authorization";
  attributes: {
    amount: number;
    cardLast4Digits: string;
    merchantName: string;
    merchantType: number;
    merchantLocation?: string;
    status?: string;
    recurring?: boolean;
    merchantId?: string;
  };
  relationships: Relationships;
}
export interface Relationships {
  account: {
    data: {
      type: "depositAccount";
      id: string;
    };
  };
}
