/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateDispute {
  data: CreateSandboxDispute;
}
export interface CreateSandboxDispute {
  type: "dispute";
  attributes: {
    amount?: number;
  };
  relationships: Relationships;
}
export interface Relationships {
  account: {
    data: {
      type: "account";
      id: string;
    };
  };
  transaction: {
    data: {
      type: "transaction";
      id: string;
    };
  };
}
