/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Officer =
  | {
      ssn: string;
    }
  | {
      passport: string;
      nationality: string;
    }
  | {
      matriculaConsular: string;
    };
export type BeneficialOwner =
  | {
      ssn: string;
    }
  | {
      passport: string;
      nationality: string;
    }
  | {
      matriculaConsular: string;
    };
export type ApplicationFormAdditionalDisclosures = {
  title?: string;
  url?: string;
}[];

export interface CreateApplicationForm {
  data: CreateApplicationForm1;
}
export interface CreateApplicationForm1 {
  type: "applicationForm";
  attributes?: {
    email?: string;
    tags?: Tags;
    applicantDetails?: ApplicationFormPrefilled;
    settingsOverride?: SettingsOverride;
    allowedApplicationTypes?: ("Individual" | "Business" | "SoleProprietorship")[];
    lang?: "en" | "es";
  };
  relationships?: {
    application?: {
      data?: {
        id?: string;
        type?: "application";
      };
    };
  };
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface ApplicationFormPrefilled {
  applicationType?: "Individual" | "Business" | "SoleProprietorship";
  fullName?: FullName;
  ssn?: string;
  passport?: string;
  nationality?: string | null;
  dateOfBirth?: string;
  email?: string;
  name?: string;
  stateOfIncorporation?: string;
  entityType?: "Corporation" | "LLC" | "Partnership";
  contact?: Contact;
  officer?: Officer;
  beneficialOwners?: BeneficialOwner[];
  website?: string;
  phone?: Phone | Phone1;
  address?: Address | Address1 | Address2;
  dba?: string;
  ein?: string;
  jwtSubject?: string | null;
  industry?:
    | "Retail"
    | "Wholesale"
    | "Restaurants"
    | "Hospitals"
    | "Construction"
    | "Insurance"
    | "Unions"
    | "RealEstate"
    | "FreelanceProfessional"
    | "OtherProfessionalServices"
    | "OnlineRetailer"
    | "OtherEducationServices";
}
export interface FullName {
  first: string;
  last: string;
}
export interface Contact {
  fullName?: FullName;
  email?: string;
  phone?: Phone | Phone1;
  jwtSubject?: string | null;
}
export interface Phone {
  countryCode: string;
  number: string;
}
export interface Phone1 {
  countryCode: string;
  number: string;
}
export interface Address {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "US";
}
export interface Address1 {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "CA";
}
export interface Address2 {
  street: string;
  street2?: string | null;
  city: string;
  state?: null | string;
  postalCode: string;
  country: string;
}
export interface SettingsOverride {
  redirectUrl?: string;
  privacyPolicyUrl?: string;
  electronicDisclosuresUrl?: string;
  depositTermsUrl?: string;
  clientTermsUrl?: string;
  cardholderTermsUrl?: string;
  cashAdvancedTermsUrl?: string;
  debitCardDisclosureUrl?: string;
  additionalDisclosures?: ApplicationFormAdditionalDisclosures;
  validatePhoneNumber?: boolean;
}
