/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateSimulatedWirePayment {
  data: CreateSimulatedWirePayment1;
}
export interface CreateSimulatedWirePayment1 {
  type: "wirePayment";
  attributes: {
    amount: number;
    description: string;
  };
  relationships: Relationships;
}
export interface Relationships {
  account: {
    data: {
      type: "depositAccount";
      id: string;
    };
  };
}
