/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateCounterparty {
  data: CreateCounterparty1 | CreateCounterparty2;
}
export interface CreateCounterparty1 {
  type: "achCounterparty";
  attributes: {
    routingNumber: string;
    accountNumber: string;
    accountType: "Checking" | "Savings";
    permissions?: "CreditOnly" | "DebitOnly" | "CreditAndDebit";
    type: "Business" | "Person" | "Unknown";
    name: string;
    tags?: Tags;
    idempotencyKey?: string;
  };
  relationships: Relationships;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface Relationships {
  customer: {
    data: {
      type: "customer";
      id: string;
    };
  };
}
export interface CreateCounterparty2 {
  type: "achCounterparty";
  attributes: {
    type: "Business" | "Person" | "Unknown";
    name?: string;
    verifyName?: boolean;
    plaidProcessorToken: string;
    permissions?: "CreditOnly" | "DebitOnly" | "CreditAndDebit";
    tags?: Tags;
    idempotencyKey?: string;
  };
  relationships: Relationships;
}
