/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateSimulatedPurchase {
  data: CreateSimulatedPurchase1;
}
export interface CreateSimulatedPurchase1 {
  type: "purchaseTransaction";
  attributes: {
    amount: number;
    direction: "Credit" | "Debit";
    merchantName: string;
    merchantType: number;
    merchantLocation?: string;
    merchantId?: string;
    coordinates?: Coordinates;
    last4Digits: string;
    recurring?: boolean;
    internationalServiceFee?: number;
  };
  relationships: Relationships;
}
export interface Coordinates {
  longitude: number;
  latitude: number;
}
export interface Relationships {
  account: {
    data: {
      type: "depositAccount" | "creditAccount";
      id: string;
    };
  };
  authorization?: {
    data: {
      type: "authorization";
      id: string;
    };
  };
}
