/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateCheckDeposit {
  data: CheckDeposit;
}
export interface CheckDeposit {
  type: "checkDeposit";
  attributes: {
    amount: number;
    description: string;
    idempotencyKey?: string;
    tags?: Tags;
  };
  relationships: Relationships;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface Relationships {
  account: {
    data: {
      type: "account" | "depositAccount" | "batchAccount";
      id: string;
    };
  };
}
