/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Schedule = CreateMonthlySchedule;

export interface CreateRecurringPayment {
  data: CreateRecurringCreditACHPayment | CreateRecurringCreditBookPayment;
}
export interface CreateRecurringCreditACHPayment {
  type: "recurringCreditAchPayment";
  attributes: {
    amount: number;
    description: string;
    addenda?: string;
    idempotencyKey?: string;
    tags?: Tags;
    schedule: Schedule;
  };
  relationships: {
    account: AccountRelationship;
    counterparty: CounterpartyRelationship;
  };
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface CreateMonthlySchedule {
  startTime?: string;
  endTime?: string;
  dayOfMonth: number;
  interval: "Monthly";
  totalNumberOfPayments?: number;
}
export interface AccountRelationship {
  data: {
    type: "account" | "depositAccount" | "creditAccount" | "batchAccount";
    id: string;
  };
}
export interface CounterpartyRelationship {
  data: {
    type: "account" | "depositAccount" | "counterparty";
    id: string;
  };
}
export interface CreateRecurringCreditBookPayment {
  type: "recurringCreditBookPayment";
  attributes: {
    amount: number;
    description: string;
    idempotencyKey?: string;
    tags?: Tags;
    transactionSummaryOverride?: string;
    schedule: Schedule;
  };
  relationships: {
    account: AccountRelationship;
    counterpartyAccount: CounterpartyAccountRelationship;
  };
}
export interface CounterpartyAccountRelationship {
  data: {
    type: "account" | "depositAccount";
    id: string;
  };
}
