/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateSimulatedPurchaseAuthorizationRequest {
  data: CreateSimulatedPurchaseAuthorizationRequest1;
}
export interface CreateSimulatedPurchaseAuthorizationRequest1 {
  type: "purchaseAuthorizationRequest";
  attributes: {
    amount: number;
    merchantName: string;
    merchantType: number;
    merchantLocation?: string;
    recurring?: boolean;
    healthcareAmounts?: HealthcareAmounts;
    ecommerce?: boolean;
    cardPresent?: boolean;
    merchantId?: string;
  };
  relationships: Relationships;
}
export interface HealthcareAmounts {
  transitAmount: number;
  prescriptionRXAmount: number;
  visionOpticalAmount: number;
  clinicOtherQualifiedMedicalAmount: number;
  dentalAmount: number;
  totalHealthcareAmount: number;
}
export interface Relationships {
  card: {
    data: {
      type: "card";
      id: string;
    };
  };
}
