/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreatePaymentsInBulk {
  data: (CreateACHPayment | CreateACHPayment1 | CreateACHPayment2 | CreateBookPayment | CreateWirePayment)[];
}
export interface CreateACHPayment {
  type: "achPayment";
  attributes: {
    amount: number;
    description: string;
    addenda?: string;
    direction: "Debit" | "Credit";
    counterparty: Counterparty;
    idempotencyKey?: string;
    sameDay?: boolean;
    tags?: Tags;
  };
  relationships: {
    account: AccountRelationship;
  };
}
export interface Counterparty {
  routingNumber: string;
  accountNumber: string;
  accountType: "Checking" | "Savings";
  name: string;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface AccountRelationship {
  data: {
    type: "account" | "depositAccount" | "creditAccount" | "batchAccount";
    id: string;
  };
}
export interface CreateACHPayment1 {
  type: "achPayment";
  attributes: {
    amount: number;
    description: string;
    addenda?: string;
    direction: "Debit" | "Credit";
    sameDay?: boolean;
    idempotencyKey?: string;
    tags?: Tags;
    verifyCounterpartyBalance?: boolean;
  };
  relationships: {
    account: AccountRelationship;
    counterparty: CounterpartyRelationship;
  };
}
export interface CounterpartyRelationship {
  data: {
    type: "account" | "depositAccount" | "counterparty";
    id: string;
  };
}
export interface CreateACHPayment2 {
  type: "achPayment";
  attributes: {
    amount: number;
    description: string;
    addenda?: string;
    direction: "Debit" | "Credit";
    idempotencyKey?: string;
    tags?: Tags;
    plaidProcessorToken: string;
    counterpartyName?: string;
    sameDay?: boolean;
    verifyCounterpartyBalance?: boolean;
  };
  relationships: {
    account: AccountRelationship;
  };
}
export interface CreateBookPayment {
  type: "bookPayment";
  attributes: {
    amount: number;
    direction?: "Debit" | "Credit";
    description: string;
    idempotencyKey?: string;
    tags?: Tags;
    transactionSummaryOverride?: string;
  };
  relationships: {
    account: AccountRelationship;
    counterpartyAccount: CounterpartyAccountRelationship;
  };
}
export interface CounterpartyAccountRelationship {
  data: {
    type: "account" | "depositAccount";
    id: string;
  };
}
export interface CreateWirePayment {
  type: "wirePayment";
  attributes: {
    amount: number;
    direction?: "Credit";
    description: string;
    counterparty: WireCounterparty;
    idempotencyKey?: string;
    tags?: Tags;
  };
  relationships: {
    account: AccountRelationship;
  };
}
export interface WireCounterparty {
  routingNumber: string;
  accountNumber: string;
  name: string;
  address: Address | Address1 | Address2;
}
export interface Address {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "US";
}
export interface Address1 {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "CA";
}
export interface Address2 {
  street: string;
  street2?: string | null;
  city: string;
  state?: null | string;
  postalCode: string;
  country: string;
}
