/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateCard {
  data:
    | CreateBusinessDebitCard
    | CreateIndividualDebitCard
    | CreateBusinessVirtualDebitCard
    | CreateIndividualVirtualDebitCard
    | CreateBusinessCreditCard
    | CreateBusinessVirtualCreditCard;
}
export interface CreateBusinessDebitCard {
  type: "businessDebitCard";
  attributes: {
    shippingAddress?: Address | Address1 | Address2;
    address: Address | Address1 | Address2;
    fullName: FullName;
    phone: Phone | Phone1;
    email: string;
    dateOfBirth: string;
    nationality?: string;
    ssn?: string;
    passport?: string;
    design?: string;
    additionalEmbossedText?: string;
    tags?: Tags;
    limits?: CardLevelLimits;
    idempotencyKey?: string;
    digitallyActive?: boolean;
  };
  relationships: Relationships;
}
export interface Address {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "US";
}
export interface Address1 {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "CA";
}
export interface Address2 {
  street: string;
  street2?: string | null;
  city: string;
  state?: null | string;
  postalCode: string;
  country: string;
}
export interface FullName {
  first: string;
  last: string;
}
export interface Phone {
  countryCode: string;
  number: string;
}
export interface Phone1 {
  countryCode: string;
  number: string;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface CardLevelLimits {
  dailyWithdrawal?: number;
  dailyPurchase?: number;
  monthlyWithdrawal?: number;
  monthlyPurchase?: number;
}
export interface Relationships {
  account: {
    data: {
      type: "depositAccount" | "creditAccount" | "account";
      id: string;
    };
  };
  customer?: {
    data: {
      type: "customer";
      id: string;
    };
  };
}
export interface CreateIndividualDebitCard {
  type: "individualDebitCard";
  attributes: {
    shippingAddress?: Address | Address1 | Address2;
    design?: string;
    tags?: Tags;
    limits?: CardLevelLimits;
    idempotencyKey?: string;
    bin?: BIN;
    cardQualifier?: string;
    cardDesignId?: string;
    additionalEmbossedText?: string;
    digitallyActive?: boolean;
  };
  relationships: Relationships;
}
export interface BIN {
  bin: string;
  institutionId: string;
}
export interface CreateBusinessVirtualDebitCard {
  type: "businessVirtualDebitCard";
  attributes: {
    address: Address | Address1 | Address2;
    fullName: FullName;
    phone: Phone | Phone1;
    email: string;
    dateOfBirth: string;
    nationality?: string;
    ssn?: string;
    passport?: string;
    tags?: Tags;
    limits?: CardLevelLimits;
    idempotencyKey?: string;
  };
  relationships: Relationships;
}
export interface CreateIndividualVirtualDebitCard {
  type: "individualVirtualDebitCard";
  attributes: {
    tags?: Tags;
    limits?: CardLevelLimits;
    idempotencyKey?: string;
    bin?: BIN;
    cardQualifier?: string;
  };
  relationships: Relationships;
}
export interface CreateBusinessCreditCard {
  type: "businessCreditCard";
  attributes: {
    shippingAddress?: Address | Address1 | Address2;
    address: Address | Address1 | Address2;
    fullName: FullName;
    phone: Phone | Phone1;
    email: string;
    dateOfBirth: string;
    nationality?: string;
    ssn?: string;
    passport?: string;
    design?: string;
    additionalEmbossedText?: string;
    tags?: Tags;
    limits?: CardLevelLimits;
    idempotencyKey?: string;
    digitallyActive?: boolean;
  };
  relationships: Relationships;
}
export interface CreateBusinessVirtualCreditCard {
  type: "businessVirtualCreditCard";
  attributes: {
    address: Address | Address1 | Address2;
    fullName: FullName;
    phone: Phone | Phone1;
    email: string;
    dateOfBirth: string;
    nationality?: string;
    ssn?: string;
    passport?: string;
    tags?: Tags;
    limits?: CardLevelLimits;
    idempotencyKey?: string;
  };
  relationships: Relationships;
}
