/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateSimulatedAtmAuthorizationRequest {
  data: CreateSimulatedAtmAuthorizationRequest1;
}
export interface CreateSimulatedAtmAuthorizationRequest1 {
  type: "atmAuthorizationRequest";
  attributes: {
    amount: number;
    atmName: string;
    atmLocation?: string;
  };
  relationships: Relationships;
}
export interface Relationships {
  card: {
    data: {
      type: "card";
      id: string;
    };
  };
}
