/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateCustomerTokenVerification {
  data: CreateCustomerTokenVerification1;
}
export interface CreateCustomerTokenVerification1 {
  type: "customerTokenVerification";
  attributes: {
    channel: "sms" | "call";
    phone?: Phone | Phone1;
    appHash?: string;
    language?:
      | "en"
      | "af"
      | "ar"
      | "ca"
      | "zh"
      | "zh-CN"
      | "zh-HK"
      | "hr"
      | "cs"
      | "da"
      | "nl"
      | "en-GB"
      | "et"
      | "fi"
      | "fr"
      | "de"
      | "el"
      | "he"
      | "hi"
      | "hu"
      | "id"
      | "it"
      | "ja"
      | "kn"
      | "ko"
      | "ms"
      | "mr"
      | "nb"
      | "pl"
      | "pt-BR"
      | "pt"
      | "ro"
      | "ru"
      | "sk"
      | "es"
      | "sv"
      | "tl"
      | "te"
      | "th"
      | "tr"
      | "vi";
  };
}
export interface Phone {
  countryCode: string;
  number: string;
}
export interface Phone1 {
  countryCode: string;
  number: string;
}
