/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DeclinedIncomingPaymentsResource {
  data: DeclinedIncomingPayment[];
}
export interface DeclinedIncomingPayment {
  type?: "declinedIncomingPayment";
  id?: string;
  attributes?: {
    amount?: number | null;
    direction?: ("Credit" | "Debit") | null;
    reason: string;
    paymentType: "AchPayment";
    createdAt: string;
  };
  relationships?: Relationships;
}
export interface Relationships {
  data?: {
    [k: string]: unknown;
  };
}
