/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DisputeDocument {
  data: DisputeResource;
}
export interface DisputeResource {
  type: "dispute";
  id: string;
  attributes?: {
    source: "DebitCard" | "ACH";
    externalId: string;
    link?: null | string;
    description: string;
    amount: number;
    status: "InvestigationStarted" | "ProvisionallyCredited" | "Denied" | "ResolvedLost" | "ResolvedWon";
    statusHistory?: {
      type?: "InvestigationStarted" | "ProvisionallyCredited" | "Denied" | "ResolvedLost" | "ResolvedWon";
      updatedAt?: string;
    }[];
    createdAt: string;
    decisionReason?: null | string;
  };
  relationships: Relationships;
}
export interface Relationships {
  customer: {
    data: {
      type: "customer";
      id: string;
    };
  };
  account: {
    data: {
      type: "account";
      id: string;
    };
  };
  transaction: {
    data: {
      type: "transaction";
      id: string;
    };
  };
}
