/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ApplicationDocumentsDocument {
  data: Document[];
  included?: unknown[];
}
export interface Document {
  type: "document";
  id: string;
  attributes: {
    documentType: string;
    status: string;
    description: string;
    nationality?: string;
    ssn?: string;
    passport?: string;
    matriculaConsular?: string;
    name?: string;
    address?: Address | Address1 | Address2;
    dateOfIncorporation?: string;
    stateOfIncorporation?: string;
    dateOfBirth?: string;
    ein?: string;
    reasonCode?: string;
    reason?: string;
    evaluationId?: string;
    frontDocumentId?: string;
    backDocumentId?: string;
    frontDocumentStoreId?: string;
    backDocumentStoreId?: string;
  };
}
export interface Address {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "US";
}
export interface Address1 {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "CA";
}
export interface Address2 {
  street: string;
  street2?: string | null;
  city: string;
  state?: null | string;
  postalCode: string;
  country: string;
}
