/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EnabledCardToCardPayment = EnabledAstraCardToCardPayment | EnabledTabapayCardToCardPayment;

export interface EnabledAstra {
  data: EnabledCardToCardPayment;
}
export interface EnabledAstraCardToCardPayment {
  type: "astra";
  id: string;
  attributes: {
    astraCardId: string;
  };
  additionalProperties?: false;
}
export interface EnabledTabapayCardToCardPayment {
  type: "tabapay";
  id: string;
  attributes: {
    tabapayAccountId: string;
  };
  additionalProperties?: false;
}
