/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FreezeAccount {
  data: FreezeDepositAccount | FreezeCreditAccount;
}
export interface FreezeDepositAccount {
  type: "accountFreeze";
  attributes: FreezeAccountFraud | FreezeAccountOther;
  additionalProperties?: false;
}
export interface FreezeAccountFraud {
  reason?: "Fraud";
}
export interface FreezeAccountOther {
  reason?: "Other";
  reasonText?: string;
}
export interface FreezeCreditAccount {
  type: "creditAccountFreeze";
  attributes: FreezeAccountFraud1 | FreezeAccountOther1;
  additionalProperties?: false;
}
export interface FreezeAccountFraud1 {
  reason?: "Fraud";
}
export interface FreezeAccountOther1 {
  reason?: "Other";
  reasonText?: string;
}
