/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IncreaseSimulatedAuthorization {
  data: IncreaseAmountSimulatedAuthorization;
}
export interface IncreaseAmountSimulatedAuthorization {
  type: "authorization";
  attributes: {
    amount: number;
    cardLast4Digits: string;
    recurring?: boolean;
  };
  relationships: Relationships;
}
export interface Relationships {
  account: {
    data: {
      type: "depositAccount";
      id: string;
    };
  };
}
