/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AccountLimitsResource {
  data: DepositAccountLimits | CreditAccountLimits;
}
export interface DepositAccountLimits {
  type: "limits";
  attributes: {
    ach: {
      limits: {
        dailyDebit: number;
        dailyCredit: number;
        monthlyDebit: number;
        monthlyDebitSoft?: number;
        dailyDebitSoft?: number;
        monthlyCredit: number;
      };
      totalsDaily: {
        debits: number;
        credits: number;
      };
      totalsMonthly: {
        debits: number;
        credits: number;
      };
    };
    card: {
      limits: {
        dailyWithdrawal: number;
        dailyDeposit: number;
        dailyPurchase: number;
        dailyCardTransaction: number;
      };
      totalsDaily: {
        withdrawals: number;
        deposits: number;
        purchases: number;
        cardTransactions: number;
      };
    };
    checkDeposit: {
      limits: {
        daily: number;
        monthly: number;
        dailySoft: number;
        monthlySoft: number;
      };
      totalsDaily: number;
      totalsMonthly: number;
    };
  };
}
export interface CreditAccountLimits {
  type: "creditLimits";
  attributes: {
    card: {
      limits: {
        dailyWithdrawal: number;
        dailyDeposit: number;
        dailyPurchase: number;
        dailyCardTransaction: number;
      };
      totalsDaily: {
        withdrawals: number;
        deposits: number;
        purchases: number;
        cardTransactions: number;
      };
    };
  };
}
