/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ApplicationFormAdditionalDisclosures = {
  title?: string;
  url?: string;
}[];
export type ApplicationFormValidatePhoneNumber = boolean;

export interface OrgSettingsDocument {
  data: OrgSettings;
  meta?: {};
}
export interface OrgSettings {
  type: "orgSettings";
  id: string;
  attributes: {
    samlSettings?: {
      orgWorkspace: string;
      entryPoint: string;
      cert: string;
      signatureAlgorithm: string;
      enforceSSOLogin?: boolean;
    };
    jwtSettings?: {
      provider: "Auth0" | "Cognito" | "Stytch";
      jwksPath: string;
      issuer?: string;
    };
    dashboardSettings?: DashboardSettings;
    statementsSettings?: {
      statementFont?: string;
      statementLogo?: string;
      statementHeaderBackground?: string;
      statementHeaderColor?: string;
      statementPhone: string;
      statementEmail: string;
      statementRepresentativeName?: string;
    };
    applicationFormSettings?: ApplicationFormSettings;
    applicationFormDomainSettings?: ApplicationFormDomainSettings;
    generalSettings: GeneralSettings;
    createdAt: string;
    updatedAt?: string;
  };
  relationships: Relationships;
}
export interface DashboardSettings {
  whitelistSourceIps?: string;
}
export interface ApplicationFormSettings {
  applicationFormCustomCss?: string;
  applicationFormLogo?: string;
  applicationFormFavicon?: string;
  applicationFormBrandName?: string;
  applicationFormRedirectUrl?: string;
  applicationFormRedirectButtonText?: string;
  applicationFormPrivacyPolicyUrl?: string;
  applicationFormElectronicDisclosuresUrl?: string;
  applicationFormDepositTermsUrl?: string;
  applicationFormClientTermsUrl?: string;
  applicationFormCardholderTermsUrl?: string;
  applicationFormCashAdvancedTermsUrl?: string;
  applicationFormDebitCardDisclosureUrl?: string;
  applicationFormContactUsEmail?: string;
  applicationFormAdditionalDisclosures?: ApplicationFormAdditionalDisclosures;
  applicationFormValidatePhoneNumber?: ApplicationFormValidatePhoneNumber;
}
export interface ApplicationFormDomainSettings {
  applicationFormDomain?: string;
  applicationFormCertificateStatus?: "Verified" | "Unverified";
}
export interface GeneralSettings {
  preventDuplicateIndividualApplications?: boolean;
  showSensitiveDataForPhysicalCards?: boolean;
  enableTagInheritanceForCards?: boolean;
}
export interface Relationships {
  org: {
    data: {
      type: "org";
      id: string;
    };
  };
}
