/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PatchCustomer {
  data: PatchIndividualCustomer | PatchBusinessCustomer | PatchTrustCustomer;
}
export interface PatchIndividualCustomer {
  type: "individualCustomer";
  attributes: {
    ssn?: string | null;
    passport?: string | null;
    nationality?: string | null;
    matriculaConsular?: null | string;
    address?: Address | Address1 | Address2;
    dateOfBirth?: string;
    phone?: Phone | Phone1;
    email?: string;
    ein?: string;
    dba?: string | null;
    riskRate?: "low" | "medium" | "high";
    tags?: TagsPatch;
    fullName?: FullName;
    authorizedUsers?: AuthorizedUser[];
    jwtSubject?: string | null;
  };
}
export interface Address {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "US";
}
export interface Address1 {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "CA";
}
export interface Address2 {
  street: string;
  street2?: string | null;
  city: string;
  state?: null | string;
  postalCode: string;
  country: string;
}
export interface Phone {
  countryCode: string;
  number: string;
}
export interface Phone1 {
  countryCode: string;
  number: string;
}
export interface TagsPatch {
  /**
   * This interface was referenced by `TagsPatch`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string | null;
}
export interface FullName {
  first: string;
  last: string;
}
export interface AuthorizedUser {
  fullName: FullName;
  email: string;
  phone: Phone | Phone1;
  jwtSubject?: string | null;
}
export interface PatchBusinessCustomer {
  type: "businessCustomer";
  attributes: {
    phone?: null | (Phone | Phone1);
    address?: null | (Address | Address1 | Address2);
    contact?: Contact;
    ein?: string;
    dba?: string | null;
    dateOfIncorporation?: string;
    stateOfIncorporation?: string;
    riskRate?: "low" | "medium" | "high";
    tags?: TagsPatch;
    authorizedUsers?: AuthorizedUser[];
    name?: string;
  };
}
export interface Contact {
  fullName?: FullName;
  email?: string;
  phone?: Phone | Phone1;
  jwtSubject?: string | null;
}
export interface PatchTrustCustomer {
  type: "trustCustomer";
  attributes: {
    phone?: null | (Phone | Phone1);
    address?: null | (Address | Address1 | Address2);
    contact?: Contact1;
    stateOfIncorporation?: string;
    riskRate?: "low" | "medium" | "high";
    revocability?: "Revocable" | "Irrevocable";
    sourceOfFunds?: "Inheritance" | "Salary" | "Savings" | "InvestmentReturns" | "Gifts";
    taxId?: string;
    tags?: TagsPatch;
    authorizedUsers?: AuthorizedUser[];
    name?: string;
  };
}
export interface Contact1 {
  fullName?: FullName;
  email?: string;
  phone?: Phone | Phone1;
  address?: Address | Address1 | Address2;
  jwtSubject?: string | null;
}
