/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PatchCard {
  data:
    | PatchIndividualDebitCard
    | PatchIndividualVirtualDebitCard
    | PatchBusinessDebitCard
    | PatchBusinessVirtualDebitCard
    | PatchBusinessCreditCard
    | PatchBusinessVirtualCreditCard;
}
export interface PatchIndividualDebitCard {
  type: "individualDebitCard";
  attributes: {
    shippingAddress?: null | (Address | Address1 | Address2);
    design?: string;
    tags?: TagsPatch;
    limits?: CardLevelLimits;
  };
}
export interface Address {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "US";
}
export interface Address1 {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "CA";
}
export interface Address2 {
  street: string;
  street2?: string | null;
  city: string;
  state?: null | string;
  postalCode: string;
  country: string;
}
export interface TagsPatch {
  /**
   * This interface was referenced by `TagsPatch`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string | null;
}
export interface CardLevelLimits {
  dailyWithdrawal?: number;
  dailyPurchase?: number;
  monthlyWithdrawal?: number;
  monthlyPurchase?: number;
}
export interface PatchIndividualVirtualDebitCard {
  type: "individualVirtualDebitCard";
  attributes: {
    tags?: TagsPatch;
    limits?: CardLevelLimits;
  };
}
export interface PatchBusinessDebitCard {
  type: "businessDebitCard";
  attributes: {
    shippingAddress?: null | (Address | Address1 | Address2);
    address?: Address | Address1 | Address2;
    phone?: Phone | Phone1;
    email?: string;
    design?: string;
    tags?: TagsPatch;
    limits?: CardLevelLimits;
  };
}
export interface Phone {
  countryCode: string;
  number: string;
}
export interface Phone1 {
  countryCode: string;
  number: string;
}
export interface PatchBusinessVirtualDebitCard {
  type: "businessVirtualDebitCard";
  attributes: {
    address?: Address | Address1 | Address2;
    phone?: Phone | Phone1;
    email?: string;
    tags?: TagsPatch;
    limits?: CardLevelLimits;
  };
}
export interface PatchBusinessCreditCard {
  type: "businessCreditCard";
  attributes: {
    shippingAddress?: null | (Address | Address1 | Address2);
    address?: Address | Address1 | Address2;
    phone?: Phone | Phone1;
    email?: string;
    design?: string;
    tags?: TagsPatch;
    limits?: CardLevelLimits;
  };
}
export interface PatchBusinessVirtualCreditCard {
  type: "businessVirtualCreditCard";
  attributes: {
    address?: Address | Address1 | Address2;
    phone?: Phone | Phone1;
    email?: string;
    tags?: TagsPatch;
    limits?: CardLevelLimits;
  };
}
