/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Officer =
  | {
      ssn: string;
    }
  | {
      passport: string;
      nationality: string;
    }
  | {
      matriculaConsular: string;
    };
export type BeneficialOwner =
  | {
      ssn: string;
    }
  | {
      passport: string;
      nationality: string;
    }
  | {
      matriculaConsular: string;
    };

export interface PatchApplicationForm {
  data:
    | PatchApplicationFormChooseBusinessOrIndividual
    | PatchApplicationFormIndividualInformation
    | PatchApplicationFormBusinessInformation
    | PatchApplicationFormOfficerInformation
    | PatchApplicationFormBeneficialOwnersInformation
    | PatchApplicationFormPhoneVerification
    | PatchApplicationFormUpdateStage;
}
export interface PatchApplicationFormChooseBusinessOrIndividual {
  type?: "applicationFormChooseBusinessOrIndividual";
  attributes?: {
    applicationFormType?: string;
    /**
     * @maxItems 1
     */
    deviceFingerprints?: [] | [DeviceFingerprint] | null;
  };
}
export interface DeviceFingerprint {
  provider: "iovation";
  value: string;
}
export interface PatchApplicationFormIndividualInformation {
  type?: "applicationFormIndividualInformation";
  attributes?: {
    stage?: string;
    fullName?: FullName;
    ssn?: string;
    nationality?: string;
    passport?: string;
    address?: Address | Address1 | Address2;
    dateOfBirth?: string;
    email?: string;
    phone?: Phone | Phone1;
    ein?: string | null;
    dba?: string | null;
    industry?:
      | "Retail"
      | "Wholesale"
      | "Restaurants"
      | "Hospitals"
      | "Construction"
      | "Insurance"
      | "Unions"
      | "RealEstate"
      | "FreelanceProfessional"
      | "OtherProfessionalServices"
      | "OnlineRetailer"
      | "OtherEducationServices";
    soleProprietorship?: boolean & string;
    /**
     * @maxItems 1
     */
    deviceFingerprints?: [] | [DeviceFingerprint] | null;
  };
}
export interface FullName {
  first: string;
  last: string;
}
export interface Address {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "US";
}
export interface Address1 {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "CA";
}
export interface Address2 {
  street: string;
  street2?: string | null;
  city: string;
  state?: null | string;
  postalCode: string;
  country: string;
}
export interface Phone {
  countryCode: string;
  number: string;
}
export interface Phone1 {
  countryCode: string;
  number: string;
}
export interface PatchApplicationFormBusinessInformation {
  type?: "applicationFormBusinessInformation";
  attributes?: {
    businessName?: string;
    dba?: string | null;
    address?: Address | Address1 | Address2;
    phone?: Phone | Phone1;
    stateOfIncorporation?: string;
    entityType?: "Corporation" | "LLC" | "Partnership";
    industry?:
      | "Retail"
      | "Wholesale"
      | "Restaurants"
      | "Hospitals"
      | "Construction"
      | "Insurance"
      | "Unions"
      | "RealEstate"
      | "FreelanceProfessional"
      | "OtherProfessionalServices"
      | "OnlineRetailer"
      | "OtherEducationServices";
    ein?: string;
    website?: string;
    /**
     * @maxItems 1
     */
    deviceFingerprints?: [] | [DeviceFingerprint] | null;
  };
}
export interface PatchApplicationFormOfficerInformation {
  type?: "applicationFormOfficerInformation";
  attributes?: {
    officer?: Officer;
    businessContact?: Contact;
    /**
     * @maxItems 1
     */
    deviceFingerprints?: [] | [DeviceFingerprint] | null;
  };
}
export interface Contact {
  fullName?: FullName;
  email?: string;
  phone?: Phone | Phone1;
  jwtSubject?: string | null;
}
export interface PatchApplicationFormBeneficialOwnersInformation {
  type?: "applicationFormBeneficialOwnersInformation";
  attributes?: {
    beneficialOwners?: BeneficialOwner[];
    /**
     * @maxItems 1
     */
    deviceFingerprints?: [] | [DeviceFingerprint] | null;
  };
}
export interface PatchApplicationFormPhoneVerification {
  type?: "applicationFormPhoneVerification";
  attributes?: {
    verificationCode?: string;
    verificationToken?: string;
    /**
     * @maxItems 1
     */
    deviceFingerprints?: [] | [DeviceFingerprint] | null;
  };
}
export interface PatchApplicationFormUpdateStage {
  type?: "applicationFormUpdateStage";
  attributes?: {
    stage?: string;
    /**
     * @maxItems 1
     */
    deviceFingerprints?: [] | [DeviceFingerprint] | null;
  };
}
