/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PatchOrgSettings {
  data: PatchOrgSettings1;
}
export interface PatchOrgSettings1 {
  type: "orgSettings";
  attributes: {
    generalSettings?: {
      [k: string]: unknown;
    } | null;
    samlSettings?: {
      [k: string]: unknown;
    } | null;
    jwtSettings?: {
      [k: string]: unknown;
    } | null;
    dashboardSettings?: {
      [k: string]: unknown;
    } | null;
    statementsSettings?: {
      [k: string]: unknown;
    } | null;
    applicationFormSettings?: {
      [k: string]: unknown;
    } | null;
  };
}
