/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PaymentResource1 = ACHPayment | BookPayment | WirePayment | BillPayment;

export interface PaymentResource {
  data: PaymentResource1;
}
export interface ACHPayment {
  type: "achPayment";
  id: string;
  attributes: {
    createdAt: string;
    amount: number;
    direction: "Credit" | "Debit";
    description: string;
    addenda?: string;
    counterparty?: Counterparty;
    tags?: Tags;
    status: "Pending" | "Rejected" | "Clearing" | "Sent" | "Canceled" | "Returned";
    settlementDate?: string;
    reason?: string | null;
    expectedCompletionDate?: string;
    [k: string]: unknown;
  };
  relationships: Relationships;
}
export interface Counterparty {
  routingNumber: string;
  accountNumber: string;
  accountType: "Checking" | "Savings";
  name: string;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface Relationships {
  account?: {
    data: {
      type: "depositAccount" | "account";
      id: string;
    };
  };
  counterparty?: {
    data: {
      type: "counterparty";
      id: string;
    };
  };
  counterpartyAccount?: {
    data: {
      type: "depositAccount" | "account";
      id: string;
    };
  };
  transaction?: {
    data: {
      type: "transaction";
      id: string;
    };
  };
}
export interface BookPayment {
  type: "bookPayment";
  id: string;
  attributes: {
    createdAt: string;
    amount: number;
    direction: "Credit" | "Debit";
    description: string;
    status: "Pending" | "Rejected" | "Clearing" | "Sent" | "Canceled" | "Returned";
    settlementDate?: string;
    reason?: string | null;
  };
  relationships: Relationships;
}
export interface WirePayment {
  type: "wirePayment";
  id: string;
  attributes: {
    createdAt: string;
    amount: number;
    direction: "Credit";
    description: string;
    counterparty?: WireCounterparty;
    status: "Pending" | "Rejected" | "Clearing" | "Sent" | "Canceled" | "Returned";
    settlementDate?: string;
    reason?: string | null;
    imadOmad?: {
      imad?: string;
      omad?: string;
    };
  };
  relationships: Relationships;
}
export interface WireCounterparty {
  routingNumber: string;
  accountNumber: string;
  name: string;
  address: Address | Address1 | Address2;
}
export interface Address {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "US";
}
export interface Address1 {
  street: string;
  street2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: "CA";
}
export interface Address2 {
  street: string;
  street2?: string | null;
  city: string;
  state?: null | string;
  postalCode: string;
  country: string;
}
export interface BillPayment {
  type: "billPayment";
  id: string;
  attributes: {
    createdAt: string;
    amount: number;
    direction: "Credit" | "Debit";
    description: string;
    status: "Initialized" | "Pending" | "Rejected" | "Clearing" | "Sent" | "Canceled" | "Returned";
    reason?: string | null;
  };
  relationships: Relationships;
}
