/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ReceivedPaymentResource = ACHReceivedPayment;

export interface ReceivedPaymentsResource {
  data: ReceivedPaymentResource[];
  meta?: {};
}
export interface ACHReceivedPayment {
  type: "achReceivedPayment";
  id: string;
  attributes: {
    createdAt: string;
    status: "Pending" | "Advanced" | "Completed" | "Returned";
    amount: number;
    completionDate: string;
    wasAdvanced?: boolean;
    companyName: string;
    counterpartyRoutingNumber: string;
    description: string;
    addenda?: string;
    traceNumber: string;
    secCode: string;
    returnReason?: string;
    tags?: Tags;
  };
  relationships: Relationships;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface Relationships {
  account: {
    data: {
      type: "account";
      id: string;
    };
  };
  customer: {
    data: {
      type: "businessCustomer" | "individualCustomer" | "customer";
      id: string;
    };
  };
  receivePaymentTransaction?: {
    data: {
      type: "transaction";
      id: string;
    };
  };
  paymentAdvanceTransaction?: {
    data: {
      type: "transaction";
      id: string;
    };
  };
  repayPaymentAdvanceTransaction?: {
    data: {
      type: "transaction";
      id: string;
    };
  };
}
