/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RecurringPaymentResource = RecurringCreditACHPayment | RecurringCreditBookPayment;

export interface RecurringPaymentsResource {
  data: RecurringPaymentResource[];
  meta?: {};
}
export interface RecurringCreditACHPayment {
  type: "recurringCreditAchPayment";
  id: string;
  attributes: {
    createdAt: string;
    updatedAt?: string;
    amount: number;
    description: string;
    addenda?: string;
    tags?: Tags;
    status: "Pending" | "Active" | "Completed" | "Disabled";
    schedule: Schedule;
    numberOfPayments: number;
  };
  relationships: Relationships;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface Schedule {
  startTime?: string;
  endTime?: string;
  interval: "Monthly";
  dayOfMonth?: number;
  nextScheduledAction: string;
  totalNumberOfPayments?: number;
}
export interface Relationships {
  account?: {
    data: {
      type: "depositAccount" | "account";
      id: string;
    };
  };
  counterpartyAccount?: {
    data: {
      type: "depositAccount" | "account";
      id: string;
    };
  };
  customer?: {
    data: {
      type: "businessCustomer" | "individualCustomer" | "customer";
      id: string;
    };
  };
}
export interface RecurringCreditBookPayment {
  type: "recurringCreditBookPayment";
  id: string;
  attributes: {
    createdAt: string;
    updatedAt: string;
    amount: number;
    description: string;
    status: "Pending" | "Active" | "Completed" | "Disabled";
    schedule: Schedule;
    numberOfPayments: number;
    tags?: Tags;
  };
  relationships: Relationships;
}
