/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReturnACHPayment {
  data: ReturnACHPayment1;
}
export interface ReturnACHPayment1 {
  type: "returnAchPayment";
  attributes?: {};
  relationships: Relationships;
}
export interface Relationships {
  payment: {
    data: {
      type: "achPayment";
      id: string;
    };
  };
}
