/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReturnACHTransaction {
  data: ReturnACHTransaction1;
}
export interface ReturnACHTransaction1 {
  type: "returnAch";
  id?: string;
  attributes: {
    reason:
      | "InsufficientFunds"
      | "ReturnedPerOdfiRequest"
      | "UncollectedFunds"
      | "ConsumerPaymentUnauthorized"
      | "CustomerAdvisesNotWithTerms"
      | "CorporatePaymentUnauthorized"
      | "CreditEntryRefusedByReceiver"
      | "AccountFrozen"
      | "FileRecordEditCriteria";
  };
  relationships: Relationships;
}
export interface Relationships {
  account?: {
    data: {
      type: "depositAccount" | "account" | "batchAccount";
      id: string;
    };
  };
}
