/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SandboxWirePaymentResource {
  data: SandboxWirePayment;
}
export interface SandboxWirePayment {
  type: "wirePayment";
  id: string;
  attributes: {
    createdAt: string;
    amount: number;
    description: string;
  };
  relationships: Relationships;
}
export interface Relationships {
  account?: {
    data: {
      type: "depositAccount";
      id: string;
    };
  };
  customer?: {
    data: {
      type: "individualCustomer" | "businessCustomer" | "customer";
      id: string;
    };
  };
}
