/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SandboxCardTransactionResource {
  data: SandboxCardTransaction;
}
export interface SandboxCardTransaction {
  type: "cardTransaction";
  id: string;
  attributes: {
    createdAt: string;
    amount: number;
    direction: "Credit" | "Debit";
    balance: number;
    summary?: string;
    cardLast4Digits: string;
    internationalServiceFee?: number;
    merchant: Merchant;
    recurring: boolean;
    tags?: Tags;
  };
  relationships: Relationships;
}
export interface Merchant {
  name: string;
  type: number;
  category: string;
  location?: string;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9_]{1,128}$".
   */
  [k: string]: string;
}
export interface Relationships {
  account: {
    data: {
      type: "account";
      id: string;
    };
  };
  card?: {
    data: {
      type: "card";
      id: string;
    };
  };
  customer?: {
    data: {
      type: "businessCustomer" | "individualCustomer" | "customer";
      id: string;
    };
  };
  authorization?: {
    data: {
      type: "authorization";
      id: string;
    };
  };
}
