/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SandboxACHPaymentResource {
  data: SandboxACHPayment;
}
export interface SandboxACHPayment {
  type: "achPayment";
  id: string;
  attributes: {
    createdAt: string;
    status: "Sent" | "Returned" | "Clearing";
    amount: number;
    direction: "Credit" | "Debit";
    counterpartyName?: string;
    description: string;
    reason?: string | null;
  };
  relationships: Relationships;
}
export interface Relationships {
  account?: {
    data: {
      type: "depositAccount" | "account" | "batchAccount" | "creditAccount";
      id: string;
    };
  };
}
