/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SandboxAtmPurchaseReversal {
  data: SandboxPurchaseReversal;
}
export interface SandboxPurchaseReversal {
  type: "cardReversalTransaction";
  id: string;
  attributes: {
    createdAt: string;
    amount: number;
    balance: number;
    last4Digits?: string;
    internationalServiceFee?: number;
  };
  relationships: Relationships;
}
export interface Relationships {
  account?: {
    data: {
      type: "depositAccount" | "creditAccount" | "account";
      id: string;
    };
  };
  customer?: {
    data: {
      type: "individualCustomer" | "businessCustomer" | "customer";
      id: string;
    };
  };
  relatedTransaction?: {
    data: {
      type: "transaction";
      id: string;
    };
  };
}
