/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SandboxAtmDepositResource {
  data: SandboxAtmDeposit;
}
export interface SandboxAtmDeposit {
  type: "atmTransaction";
  id: string;
  attributes: {
    createdAt: string;
    amount: number;
    balance: number;
    atmName: string;
    atmLocation?: string;
    last4Digits?: string;
    internationalServiceFee?: number;
  };
  relationships: Relationships;
}
export interface Relationships {
  account?: {
    data: {
      type: "depositAccount";
      id: string;
    };
  };
  customer?: {
    data: {
      type: "individualCustomer" | "businessCustomer" | "customer";
      id: string;
    };
  };
}
