/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TransmitWirePayment {
  data: TransmitWirePayment1;
}
export interface TransmitWirePayment1 {
  type: "transmitWirePayment";
  attributes?: {};
  relationships: Relationships;
}
export interface Relationships {
  payment: {
    data: {
      type: "wirePayment";
      id: string;
    };
  };
}
